---
App: "aws-sso-extensions-for-enterprise"
Environment: "leela"
Version: "3.2.0"

PipelineSettings:
  BootstrapQualifier: "ssoutility" # For example: 'ssoutility'
  DeploymentAccountId: "437271226449"
  DeploymentAccountRegion: "eu-west-1"
  TargetAccountId: "270869494959"
  TargetAccountRegion: "eu-west-1"
  OrgMainAccountId: "567063574936"
  SSOServiceAccountId: "567063574936"
  SSOServiceAccountRegion: "eu-west-1"
  RepoArn: "arn:aws:codecommit:eu-west-1:437271226449:aws-sso-extensions-for-enterprise"
  RepoBranchName: "main" # Verify that this is the branch name used by your CodeCommit repository
  SynthCommand: "yarn cdk synth leela-aws-sso-extensions-for-enterprise -c config=leela"

Parameters:
  LinksProvisioningMode: "api"
  PermissionSetProvisioningMode: "s3"
  LinkCallerRoleArn: "arn:aws:iam::270869494959:role/LinkCallerRole"
  PermissionSetCallerRoleArn: "arn:aws:iam::270869494959:role/PermissionSetCallerRole"
  NotificationEmail: "klagudu+ssoex@gmail.com"
  IsAdUsed: false
  DomainName: "corp.example.com" # If IsAdUsed is false, this will be ignored.
  ImportCurrentSSOConfiguration: true
  UpgradeFromVersionLessThanV303: false # Should be set to true, if upgrading from solution version 3.0.2/earlier
